services:
  - type: web
    name: invoice-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: invoice-data
      mountPath: /opt/render/project/src/backend/database
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: ./database/users.db
    healthCheckPath: /api/health
