services:
  - type: web
    name: invoice-backend
    env: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: ./database/users.db
      - key: NODE_VERSION
        value: 18.18.0
    healthCheckPath: /api/health
